feat(release-please): add default branch input option
google-github-actions/release-please-action pull request #202
Opened 2021-01-29 23:33 UTC by pragmaticivan

Fixes https://github.com/google-github-actions/release-please-action/issues/201

2021-01-29 23:43 UTC, pragmaticivan commented
Hum... the tests are passing locally with node 14.15.4. Investigating.

2021-01-30 23:44 UTC, bcoe commented on test/release-please.js
> +  it('both opens PR to a different default branch and tags GitHub releases by default', async () => {
Thank you for the test 🎉

2021-01-30 23:46 UTC, bcoe requested changes

2021-01-30 23:46 UTC, bcoe commented on test/release-please.js
> +      run: releasePR
Mind adding the inverse too, that confirms we default to `undefined` for the default branch? (at which point the default branch is currently detected).

2021-01-30 23:46 UTC, bcoe commented
@pragmaticivan thank you for the contribution, one thought about a good additional test.

2021-01-31 01:09 UTC, pragmaticivan commented
@bcoe just added a slight change on the test covering both. I felt it made more sense to complement the first test (default branch) as my change was a variation of the first one.

2021-01-31 01:27 UTC, pragmaticivan commented
@bcoe I've also added this input into the readme. Missed that part.

2021-01-31 02:29 UTC, bcoe approved these changes

2021-01-31 02:29 UTC, merged