feat(release-please): add default token input option
set the ${{ secrets.GITHUB_TOKEN }} as the default input of token.

The ${{ github.token }} can access to it.

Close #211
google-github-actions/release-please-action pull request #212
Opened 2021-02-12 15:07 UTC by yi-Xu-0100

2021-02-12 15:10 UTC, yi-Xu-0100 commented
@googlebot I signed it!

2021-02-12 15:52 UTC, pragmaticivan commented
It might be worth adding an example of using a custom token instead of GITHUB_TOKEN as it's still a valid input.

2021-02-12 16:20 UTC, yi-Xu-0100 commented
@pragmaticivan I tried to add an example usage for the personal access token. 😃

2021-02-13 00:25 UTC, yi-Xu-0100 commented
Hey @bcoe, I have been using this feature (use default token for action) in my actions for a long time. e.g., [yi-Xu-0100/repo-list-generator](https://github.com/yi-Xu-0100/repo-list-generator) and [yi-Xu-0100/traffic-to-badge](https://github.com/yi-Xu-0100/traffic-to-badge). What else do I need to do to merge this PR?

2021-02-13 19:07 UTC, bcoe commented
@yi-Xu-0100 I'm slightly surprised by this feature, because it means that an upstream action can get the GITHUB_TOKEN, without it explicitly being set as inputs.

Is there a step where an action needs to opt in? this is interesting from a security perspective for actions.

2021-02-14 06:18 UTC, yi-Xu-0100 commented
@bcoe 

`github.token` used as the default input value of the token in the official actions([checkout](https://github.com/actions/checkout/blob/25a956c84d5dd820d28caab9f86b8d183aeeff3d/action.yml#L24), [stale](https://github.com/actions/stale/blob/07f3f88b6d7554724b296fec903b4635a085f4dc/action.yml#L8), [github-script](https://github.com/actions/github-script/blob/b251c3e139ca75460518e90ba9800f97235e9ae7/action.yml#L13)) is also very common. I think that the reasons are as follows:
1. The permission of `secret.GITHUB_TOKEN` is very limitation, and it is restricted to be used in workflows, and does not have the permission to obtain special data in the repository or the data in other repositories of the owner. (Reference [permissions-for-the-github_token](https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token))
2. There are steps that must use token in the current action. Token is a required item, and `secret.GITHUB_TOKEN` with the least authority is used as the default input, which may reduce repeated configuration.
3. The `github.token` can be used to obtain the same permissions as `secret.GITHUB_TOKEN`. (Reference [github-context](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context))

2021-02-15 04:12 UTC, bcoe reviewed
@yi-Xu-0100 will review tomorrow I'm hoping 👍

2021-02-15 04:12 UTC, bcoe commented on README.md
> +| `token` | A GitHub secret token, the action default use the special `secrets.GITHUB_TOKEN` |
```suggestion
| `token` | A GitHub secret token, the action defaults to using the special `secrets.GITHUB_TOKEN` |
```

2021-02-15 17:50 UTC, bcoe requested changes
Looks good to me, I think we could do without the additional section in the README. What do you think?

2021-02-15 17:50 UTC, bcoe commented on README.md
> +### Use the personal access token in fork repository
I think we could just drop this section. It's a lot of content, and I think it's clear from the description of `--token` that you can provide an alternate token if you're interested.

2021-02-15 20:07 UTC, bcoe commented
@yi-Xu-0100 @pragmaticivan if we want to keep the section about a custom token, I might just make it a short blurb, about the fact that you can use an alternate token, perhaps pointing out the `fork` option.

I don't think we need a fully fleshed out example, folks will understand they can just pass an alternate token.

2021-02-16 00:50 UTC, yi-Xu-0100 commented
@bcoe I tried to reduce the example section, hoping it could be better. 😀

2021-02-16 14:08 UTC, yi-Xu-0100 commented
@bcoe When I test for my own repository, I find the token of `secret.GITHUB_TOKEN` can be used for both the fork and private repository. 

At first, I test the fork repository, and it does well. See in https://github.com/yi-xu-test-organization/test-repo-1/pull/1 (the input value of fork is true because of the boolean input issue)

Then I set the origin repository (https://github.com/yi-Xu-0100/test-repo) was setting to be private to test the action and also got the success result.

So I delete the example section and only keep the description of the token.  😅

2021-02-16 19:03 UTC, bcoe approved these changes

2021-02-16 19:03 UTC, merged