fix: get the correct boolean value of the input
google-github-actions/release-please-action pull request #233
Opened 2021-02-16 16:34 UTC by yi-Xu-0100

1. add getBooleanInput function to get the correct boolean value of the input
2. add test for getBooleanInput function
3. add default value for the input

fix #215

2021-02-16 16:40 UTC, yi-Xu-0100 commented
@bcoe I find a bot will pull a request for build the dist, so I didn't run `npm run build`. If this is the step I need to do, tell me and I will push a commit. 😀

2021-02-16 19:00 UTC, bcoe requested changes
One nit about how we handle default value.

2021-02-16 19:00 UTC, bcoe commented on test/release-please.js
> +const defaultInput = {
```suggestion
// As defined in action.yml
const defaultInput = {
```

2021-02-17 02:45 UTC, yi-Xu-0100 commented on index.js
> +  const fork = getBooleanInput('fork') ? true : undefined
I think that the `undefined` is different from the `false`, so I keep `undefined` for logic here as the same as before.

2021-02-17 02:47 UTC, yi-Xu-0100 commented on index.js
> +  const fork = getBooleanInput('fork') ? true : undefined
I confused about the default value with boolean type. Because I cannot judge that whether the input is the same as the defined in `action.yml`(https://github.com/actions/toolkit/issues/272), and I think the default value should be set into the `action.yml` to show the type of input.

Then I tried to figure out why the `undefined` instead of the `false` for here, and I find the commit(https://github.com/googleapis/release-please/commit/5057818c9029cb2054c2279183044c17c607699f) about the fork option, which shows the fork is also a boolean type. 

Finally, I use the logical OR and logical AND to replace the ternary operation and the paser of changelogTypes. 😀

2021-02-17 19:56 UTC, bcoe approved these changes

2021-02-17 19:56 UTC, bcoe commented
@yi-Xu-0100 thank you for the contribution.

2021-02-17 19:56 UTC, merged