feat: add `bump-patch-for-minor-pre-major` option
google-github-actions/release-please-action pull request #365
Opened 2021-09-13 17:51 UTC by ilya-lesikov

Pass `bump-patch-for-minor-pre-major` to release-please to allow bumping
patch versions instead of minors for feat changes. Disabled by default.

This functionality was broken in release-please until now: https://github.com/googleapis/release-please/issues/1049
I suppose the fix should be in the new release of release-please soon.

Signed-off-by: Ilya Lesikov <ilya@lesikov.com>

2021-09-13 22:14 UTC, bcoe approved these changes

2021-09-13 22:15 UTC, bcoe requested changes
This should now be fixed in the latest release of `release-please`, could I bother you to upate the version in `package.json` as well?

2021-09-15 08:46 UTC, ilya-lesikov commented
Updated, I hope I didn't update too much in the lock file.

2021-09-23 20:44 UTC, bcoe approved these changes

2021-09-23 21:02 UTC, merged