feat: add extra-files input
google-github-actions/release-please-action pull request #410
Opened 2022-01-03 13:37 UTC by jcornaz

fix #343

Add the `extra-files` input option.

See: https://github.com/googleapis/release-please/blob/main/docs/customizing.md#updating-arbitrary-files

Important note: **It doesn't work!** (I tested on one of my rust repo). But I don't understand why. As far as I understand, it should work... @bcoe Would you mind having a look?

2022-01-03 16:44 UTC, bcoe commented
@jcornaz try installing the latest version of `release-please` and running `npm run build`.

2022-01-03 17:06 UTC, jcornaz commented
Thanks @bcoe. It does work now :-)

2022-01-12 23:36 UTC, bcoe commented
@jcornaz mind rebasing?

2022-01-13 09:37 UTC, jcornaz commented
@bcoe I rebased :+1:

2022-01-13 15:52 UTC, bcoe requested changes

2022-01-13 15:52 UTC, bcoe commented on README.md
> +| `extra-files` | add extra-files to bump using the [generic updater](https://github.com/googleapis/release-please/blob/main/docs/customizing.md#updating-arbitrary-files) |
A small additional example in README.md, that demonstrates how to provide multiline input I think would be valuable, I assume it's:

```
extra-files:
  - file a
  - file b
```?

2022-01-13 16:25 UTC, jcornaz commented on README.md
> +| `extra-files` | add extra-files to bump using the [generic updater](https://github.com/googleapis/release-please/blob/main/docs/customizing.md#updating-arbitrary-files) |
Yes, I'll add an example.

Here is how to provide multiline inputs:

```
extra-files: |
  file1
  file2
```

IMO the syntax you mentioned would have bean nicer, because that's how we are used to define lists in yaml, but github actions uses *multi-line* input instead: https://github.com/actions/toolkit/pull/829

2022-01-13 16:30 UTC, jcornaz commented on README.md
> +| `extra-files` | add extra-files to bump using the [generic updater](https://github.com/googleapis/release-please/blob/main/docs/customizing.md#updating-arbitrary-files) |
@bcoe I am not sure where I should add the example in the readme. Should it be directly in the table of inputs? Or should I add a dedicated section later in the readme?

2022-01-13 16:44 UTC, bcoe commented on README.md
> +| `extra-files` | add extra-files to bump using the [generic updater](https://github.com/googleapis/release-please/blob/main/docs/customizing.md#updating-arbitrary-files) |
@jcornaz I'd just add an extra section after:

`Creating major/minor tags`

Along the lines of  `Adding additional files`.

2022-01-17 18:56 UTC, bcoe approved these changes

2022-01-17 18:58 UTC, merged

2022-01-17 18:59 UTC, bcoe commented
@jcornaz thank you 🥳

2022-07-12 10:39 UTC, patoncrispy commented
How does this work with updating xml or json files? How can I set the xpath?

2022-07-12 11:23 UTC, jcornaz commented
> How does this work with updating xml or json files? How can I set the xpath?

You cannot set a XPath. In the file you want to update, you have to comment in the file where are the part want to update. See: https://github.com/googleapis/release-please/blob/main/docs/customizing.md#updating-arbitrary-files for more details

Example:

```xml
<myxml>
  <version>1.0.0</version> <!-- x-release-please-version -->
</myxml>
```

2022-07-13 04:28 UTC, patoncrispy commented
Thanks @jcornaz . I've tried that with the `simple` strategy but it's ignoring the `extra-files` option. At least, I cannot see anything in the output and there's no change in the PR it creates. Are there any examples of how to use this? The docs are pretty light. 
![image](https://user-images.githubusercontent.com/2559414/178650829-d2d65b40-a35b-4f4c-8f7b-6830d73d2fde.png)

2022-07-13 07:05 UTC, jcornaz commented
Mmh strange, it should work. I suggest you open an issue and share an example of how to reproduce.