feat: release-please-action now read GitHub action context.
google-github-actions/release-please-action pull request #532
Opened 2022-07-19 04:00 UTC by goatwu1993

Fix #508

This allowed GitHub Enterprise users to use this action without specifying github-api-url and github-graphql-url

2022-07-20 06:29 UTC, goatwu1993 commented
Works on my site.

2022-07-27 03:09 UTC, goatwu1993 commented
@chingor13 please take a look.

2022-08-10 16:33 UTC, chingor13 requested changes
This looks good, except the tests are failing.

Looks like `core.getInput()` returns undefined if not set

2022-08-10 18:13 UTC, chingor13 approved these changes

2022-08-10 18:13 UTC, merged